### ISSUE TITLE
Position is outside of object

### ISSUE THREAD

**Issue by BeloCraft** [Infactum/onec_dtools#4]
Пытаюсь прочитать базу 1С 8.3 (Управление медицинским центром) и получаю такую вещь, ранее было все хорошо и работало с этой базой.

Position is outside of object.
Traceback (most recent call last):
  File "service.py", line 71, in <module>
  File "service.py", line 60, in main
  File "<string>", line 108, in parse
  File "C:\Users\py34\Desktop\Awesome\sql1c.py", line 157, in convert
  File "C:\Python34\lib\site-packages\onec_dtools\database_reader.py", line 552, in as_dict
  File "C:\Python34\lib\site-packages\onec_dtools\database_reader.py", line 614, in value
  File "C:\Python34\lib\site-packages\onec_dtools\database_reader.py", line 614, in <listcomp>
  File "C:\Python34\lib\site-packages\onec_dtools\database_reader.py", line 634, in __iter__
  File "C:\Python34\lib\site-packages\onec_dtools\database_reader.py", line 341, in seek
IndexError: Position is outside of object

**Comment by Infactum** [comment]
Необходимо больше деталей.
Для начала не плохо бы проверить, что база не битая, сделав внешнее тестирование.
Если не поможет, то нужно пробовать воспроизвести ошибку на некой "демо" базе, которую вы сможете предоставить.

**Comment by BeloCraft** [comment]
Хорошо, сообщу клиенту, чтобы провел внешнее тестирование базы и отпишусь, спасибо!

**Comment by BeloCraft** [comment]
Действительно были проблемы с базой данных. Помогло тестирование через конфигуратор.
